name: Build WhatsApp Companion APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Extract Android project
        run: |
          mkdir build-project
          unzip -q *.zip -d build-project
          ls -la build-project

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.11.1'

           - name: Make WebView look like desktop Chrome
        run: |
          sed -i 's#Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/131.0 Mobile Safari/537.36#Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36#' build-project/app/src/main/java/com/example/whatsappcompanion/MainActivity.java

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WhatsApp-Companion-APK
          path: build-project/app/build/outputs/apk/debug/app-debug.apk
